[package]
name = "pcp_mmv"
version = "0.1.0"
authors = ["Saurav Sachidanand <sauravsachidanand@gmail.com>"]
build = "build.rs"

[dependencies]
inotify = "0.4"
nickel = "0.9.0"
rand = "0.3.15"
sha2 = "0.5.2"